import { SimulationEngine } from './engine';
import { AsyncContext } from './async-context';
import { FaultDriver } from './driver';
import { ProgrammaticPromise, executePromise, createPromiseContext } from './promise';
import { SimulationRun, FaultScheduleTemplate, FaultSchedule, PromiseResult, FaultScheduleSchema } from '@sibyl-shared';
import { z } from 'zod';
import { PRNG } from './prng';
import * as crypto from 'crypto';

import { SearchStrategy } from './search/strategy';
import { Ucb1SearchStrategy } from './search/ucb1';
import { SandboxProvider, Sandbox } from './sandbox/provider';

export interface SearchConfig {
  workflow: () => Promise<void>;
  templates: FaultScheduleTemplate[];
  promises: ProgrammaticPromise[];
  iterations: number;
  concurrency?: number;
  earlyExit?: boolean; // Stop if ANY promise fails
  seed?: string;
  clockOptions?: { mode: 'realtime' | 'accelerated', skewMs?: number };
  strategy?: SearchStrategy;
  sandboxProvider?: SandboxProvider;
}

export interface SearchResult {
  totalRuns: number;
  failures: number;
  passes: number;
  errored: number;
  worstRun?: {
    runId: string;
    seed: string;
    concreteSchedules: FaultSchedule[];
    promiseResults: PromiseResult[];
    status: SimulationRun['status'];
    error?: string;
  };
  results: {
    runId: string;
    seed: string;
    concreteSchedules: FaultSchedule[];
    promiseResults: PromiseResult[];
    passed: boolean;
    status: SimulationRun['status'];
    error?: string;
  }[];
}

export class SearchOrchestrator {
  private masterSeed: string;
  private prng: PRNG;
  private drivers: FaultDriver[] = [];
  private strategy: SearchStrategy;

  constructor(private config: SearchConfig) {
    this.masterSeed = config.seed || crypto.randomUUID();
    this.prng = new PRNG(this.masterSeed);
    this.strategy = config.strategy || new Ucb1SearchStrategy(config.templates, this.masterSeed);
  }

  registerDriver(driver: FaultDriver) {
    this.drivers.push(driver);
  }

  // generateConcreteSchedules is replaced by strategy.next()

  async run(): Promise<SearchResult> {
    const results: SearchResult['results'] = [];
    let earlyExited = false;
    let worstRun: SearchResult['worstRun'] | undefined;

    const concurrency = this.config.concurrency || 1;
    let iterationsDone = 0;

    // We must install drivers ONCE in the process, but we install them with an AsyncContext-aware proxy context.
    this.installContextAwareDrivers();

    const workerQueue = Array.from({ length: this.config.iterations }, (_, i) => i);

    const worker = async () => {
      while (workerQueue.length > 0 && !earlyExited) {
        const i = workerQueue.shift()!;
        
        let schedules: FaultSchedule[] = [];
        let runStatus: SimulationRun['status'] = 'PENDING';
        let runError: string | undefined;

        try {
          // Ask the strategy for the next schedules and strictly validate
          const rawSchedules = this.strategy.next(iterationsDone);
          schedules = z.array(FaultScheduleSchema).parse(rawSchedules);
        } catch (e: any) {
          runStatus = 'ERRORED';
          runError = `Malformed FaultSchedule generated by strategy: ${e.message}`;
        }
        
        // We still need a runSeed to initialize the engine's PRNG for the RUN
        // The orchestrator just forks one for each iteration so the engine has a deterministic base
        const runSeed = this.prng.fork(`run-${i}`).next().toString();
        
        const runId = crypto.randomUUID();
        const runConfig: SimulationRun = {
          id: runId,
          environment: this.config.sandboxProvider ? 'DOCKER_CONTAINER' : 'LOCAL_PROCESS',
          status: runStatus,
          schedules,
          ...(runError ? { error: runError } : {})
        };

        const engine = new SimulationEngine(runConfig, runSeed, this.config.clockOptions);
        
        let sandbox: Sandbox | undefined;
        if (this.config.sandboxProvider && runStatus !== 'ERRORED') {
          sandbox = await this.config.sandboxProvider.createSandbox({
            imageId: 'sibyl-default-sandbox:latest', // In reality, this comes from CLI config
            maxMemoryMb: 512,
            maxCpus: 1
          });
        }

        if (runStatus !== 'ERRORED') {
          runStatus = 'RUNNING';
          await AsyncContext.run({ runId, engine }, async () => {
            engine.start();
            try {
              if (sandbox) {
                await sandbox.start(['node', 'dist/sandbox-worker.js']);
                // The sandbox would connect back to the orchestrator to fetch workflow and report events.
                // We'll simulate its execution finishing here.
                await sandbox.stop();
                await sandbox.cleanup();
              } else {
                await this.config.workflow();
              }
              runStatus = 'COMPLETED';
            } catch (e: any) {
              console.error(`Workflow crashed in run ${runId}`, e);
              runStatus = 'ERRORED';
              runError = `Workflow threw synchronously or crashed: ${e.message}`;
            }
            engine.stop();
          });
        }

        // Evaluate promises outside of AsyncContext
        const pCtx = createPromiseContext(runId, engine.getEvents());
        const promiseResults: PromiseResult[] = [];
        let runPassed = runStatus === 'COMPLETED';

        if (runStatus === 'COMPLETED' || runStatus === 'ERRORED') {
          for (const p of this.config.promises) {
            const res = await executePromise(p, pCtx, Date.now());
            promiseResults.push(res);
            if (!res.passed) {
              runPassed = false;
            }
          }
        }
        
        if (runStatus === 'COMPLETED' && !runPassed) {
          runStatus = 'FAILED';
        }

        const runRecord = {
          runId,
          seed: runSeed,
          concreteSchedules: schedules,
          promiseResults,
          passed: runPassed,
          status: runStatus,
          error: runError
        };

        // Send feedback to strategy
        this.strategy.feedback(runRecord);

        results.push(runRecord);

        if (!runPassed) {
          if (!worstRun || promiseResults.filter(p => !p.passed).length > worstRun.promiseResults.filter(p => !p.passed).length) {
            worstRun = runRecord;
          }
          if (this.config.earlyExit) {
            earlyExited = true;
          }
        }

        iterationsDone++;
      }
    };

    const workers = Array.from({ length: concurrency }, () => worker());
    await Promise.all(workers);

    this.uninstallDrivers();

    return {
      totalRuns: iterationsDone,
      failures: results.filter(r => r.status === 'FAILED').length,
      passes: results.filter(r => r.passed).length,
      errored: results.filter(r => r.status === 'ERRORED').length,
      worstRun,
      results
    };
  }

  /**
   * Installs the drivers globally once, but provides a Proxy context that looks up the active engine via AsyncLocalStorage.
   */
  private installContextAwareDrivers() {
    for (const driver of this.drivers) {
      driver.install({
        get clock() {
          const engine = AsyncContext.getEngine();
          if (!engine) throw new Error(`No active SimulationEngine found in AsyncLocalStorage for driver ${driver.domain}`);
          return (engine as any).clock;
        },
        getFaultDecision: (domain, meta) => {
          const engine = AsyncContext.getEngine();
          if (!engine) return null; // Or throw? If it's a background call outside a workflow context, it shouldn't be faulted.
          // In engine.ts we need to expose getFaultDecision. 
          // Let's call engine.evaluateFaultDecision(domain, meta)
          return (engine as any).evaluateFaultDecision(domain, meta);
        },
        recordEvent: (event) => {
          const engine = AsyncContext.getEngine();
          if (engine) {
             (engine as any).recordEvent(event);
          }
        }
      });
    }
  }

  private uninstallDrivers() {
    for (const driver of this.drivers) {
      driver.uninstall();
    }
  }
}
